// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-8GS7qxkkgM3wfWnkL1A9cfruLTG1QMg',
    appId: '1:999919126471:web:21cb3684fb50931efbfbe2',
    messagingSenderId: '999919126471',
    projectId: 'quiet-canto-426011-q6',
    authDomain: 'quiet-canto-426011-q6.firebaseapp.com',
    storageBucket: 'quiet-canto-426011-q6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZp5e40uCIbI_ef8AYBcP5_m6OlxDCuMI',
    appId: '1:999919126471:android:d41e6dd46a0b5ffdfbfbe2',
    messagingSenderId: '999919126471',
    projectId: 'quiet-canto-426011-q6',
    storageBucket: 'quiet-canto-426011-q6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpnQWT3QgzLbpgB59CnDNi70-35uSsR5c',
    appId: '1:999919126471:ios:5d8a73e74ad69a3afbfbe2',
    messagingSenderId: '999919126471',
    projectId: 'quiet-canto-426011-q6',
    storageBucket: 'quiet-canto-426011-q6.firebasestorage.app',
    androidClientId: '999919126471-onrtj7le85dq6queqrv1icbnrl8ov6mv.apps.googleusercontent.com',
    iosClientId: '999919126471-haumr9s175q6v2d5b84gom7hr7j98aqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpnQWT3QgzLbpgB59CnDNi70-35uSsR5c',
    appId: '1:999919126471:ios:5d8a73e74ad69a3afbfbe2',
    messagingSenderId: '999919126471',
    projectId: 'quiet-canto-426011-q6',
    storageBucket: 'quiet-canto-426011-q6.firebasestorage.app',
    androidClientId: '999919126471-onrtj7le85dq6queqrv1icbnrl8ov6mv.apps.googleusercontent.com',
    iosClientId: '999919126471-haumr9s175q6v2d5b84gom7hr7j98aqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-8GS7qxkkgM3wfWnkL1A9cfruLTG1QMg',
    appId: '1:999919126471:web:242449840203ed35fbfbe2',
    messagingSenderId: '999919126471',
    projectId: 'quiet-canto-426011-q6',
    authDomain: 'quiet-canto-426011-q6.firebaseapp.com',
    storageBucket: 'quiet-canto-426011-q6.firebasestorage.app',
  );
}
